# Generated by Django 4.1.7 on 2023-07-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_options_alter_servicio_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio La Coruña', 'verbose_name_plural': 'Servicios La Coruña'},
        ),
    ]
